/*
Problem 2 Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

$(document).ready( function() {

  sum = 0;

  function fibo(num) {
    if (num < 2) { 
      return num 
    } else {
      return fibo(num-2) + fibo(num-1)
    }
  };

  // rest of script goes below here...

   for (n=2;n<=34;n++) {
     f = fibo(n);
     if ( f >= 4000000 ) { 
       $("#output").append( "<li>Over 4 Mil! Val: " + f + " count is " +n+ "</li>" ); 
     } else if (f % 2 == 0) {
       $("#output").append("<li>"+f+"</li>");
       sum += f;
     }
   };

   $("#output").append("<h2>Sum is: "+sum+"</h2>");

});


